No squash
remotemobprogramming/mob pull request #222
Opened 2021-12-19 17:01 UTC by gregorriegler

2022-01-05 08:16 UTC, simonharrer commented
Can you add a CHANGELOG entry? Otherwise, I think this is reasonable.

2022-01-05 08:17 UTC, simonharrer commented on mob.go
> +			silentgit("reset", "--soft", "HEAD^")
I think this should not be a silentgit but a git as this is helpful for the user to see.

2022-01-05 17:24 UTC, albran requested changes
at `1018` in `mob.go`
```
if configuration.MobDoneSquash {
	if isNothingToCommit() {
		sayInfo("nothing was done, so nothing to commit")
	} else {
		sayTodo("To finish, use", "git commit")
	}
}
```

`if configuration.MobDoneSquash` could be removed to receive the same todo prompt when specifying ```--no-squash```

2022-01-05 18:48 UTC, gregorriegler commented
@simonharrer @albran 
Thank you for your inputs. Made the changes.

2022-01-07 19:36 UTC, gregorriegler commented
@simonharrer should I merge it?

2022-01-07 20:25 UTC, simonharrer commented on mob.go
> +			sayInfo("nothing was done, so nothing to commit")
When doing a merge, this message is wrong. We need two different messages, one for each option.

2022-01-07 20:26 UTC, simonharrer commented on mob.go
> +			sayInfo("nothing was done, so nothing to commit")
In case of `--no-squash` we could basically omit it. That would be fine as well.

2022-01-07 21:22 UTC, gregorriegler commented
@simonharrer you mean like this?

2022-01-08 07:30 UTC, merged