Mob timer should work anywhere on the system
remotemobprogramming/mob pull request #295
Opened 2022-07-06 15:39 UTC by maciej-stanuch

I've added a check for git availability in `getMobTimerRoom` method to allow it to work anywhere in the system.

So, now the behaviour is like this:
- If git repository -> works as it worked before
- If not a git repository -> use the room name from `MOB_TIMER_ROOM` 

---
I wonder if the code, especially `mob.go` file, shouldn't be somehow split into smaller files? It's slightly difficult to work with.
I have not much experience in Go and maybe that's not a good idea to separate all that stuff? I feel like it would make it easier to test it at least.

2022-07-07 06:15 UTC, simonharrer requested changes

2022-07-07 06:18 UTC, simonharrer commented
We could even write a test for this. As part of the testbed, there's a directory that is not a git repo. We could switch to that and call the main method with `mob timer 0` and verify that we get a specific output in the console. We should change the configuration of the notify command so that no sound output will be generated when running this test.

2022-07-12 20:27 UTC, maciej-stanuch commented
> We could even write a test for this. As part of the testbed, there's a directory that is not a git repo. We could switch to that and call the main method with mob timer 0 and verify that we get a specific output in the console. We should change the configuration of the notify command so that no sound output will be generated when running this test.

Will do, I haven't much free time recently to finish it up properly

2022-07-12 21:05 UTC, merged

2022-07-12 21:05 UTC, simonharrer commented
Feel free to create a new PR with a test for this.