fix the logging how to fix uncommited changes
remotemobprogramming/mob pull request #386
Opened 2023-05-12 15:20 UTC by hollesse

closes #383

2023-05-21 18:07 UTC, gregorriegler commented on mob_test.go
> +	os.Setenv("MOB_WIP_BRANCH_QUALIFIER", "red")
I think we should be using `t.Setenv` instead

2023-05-21 18:10 UTC, gregorriegler requested changes
other than my comment it looks good to me

2023-05-26 08:27 UTC, hollesse commented
I needed to update the go version to use t.setEnv

2023-05-27 21:01 UTC, gregorriegler approved these changes

2023-06-02 11:31 UTC, merged